TimeToolDev:
  #########################################################################################################
  Application:
    AppLane[:]:
      ###################
      Fex:
        AddValue: 0x0        
      ###################
      Prescale:
        DialInPreScaling: 0x7c
      ###################
      EventBuilder:
        Bypass:  0x1 # Ignoring trigger stream for now
  #########################################################################################################
  ClinkFeb[:]:
    ###################
    ClinkTop:
    ###################
      ###################
      Channel[:]:
        LinkMode: Base 
        DataMode: 8Bit
        FrameMode: Line
        TapCount: 4
        DataEn: True
        Blowoff: False
        BaudRate: 9600 # units of bps
        SerThrottle: 10000 # (10ms x 1us throttle rate) = 10000
        SwControlValue: 0x0
        SwControlEn: 0x0     
    ###################
    UartPiranha4[:]: # Piranha4 UART interface
      SPF: '0'     # SFP: 0 = 8-bit mode
      CLM: '2'     # CLM: 2 = full
      SVM: '0'     # SVM: test pattern mode
      SEM: '0'     # SEM: Set Exposure Mode
      SET: '5000'  # SET: Set Exposure Time
      STM: '1'     # STM: External Trigger Mode    
      SSF: '7000'
    ###################
    TrigCtrl[0]:
      EnableTrig: True
      InvCC: False
      TrigMap: ChA
      TrigPulseWidth: 0xfff
      TrigMask: 0x1
    ###################
    TrigCtrl[1]:
      EnableTrig: True
      InvCC: False
      TrigMap: ChB
      TrigPulseWidth: 0xfff
      TrigMask: 0x1
    ###################
    BoardTemp:
      RemoteTcritSetpoint: 100 # Prevent FEB from thermal shutdown until FPGA Tj = 100 degC (max. operating temp)        
  #########################################################################################################
  Hardware:
    Timing:
      ###################
      TimingDbgMon:
        Loopback: 0x0
        # UseMiniTpg: False
        UseMiniTpg: True # True for standalone testing
      ###################
      Triggering: # https://confluence.slac.stanford.edu/download/attachments/216713616/ConfigEvrV2CoreTriggersYaml.pdf
        ###################
        Ch[:]:
          EnableReg: True
          # RateSel: 0x1028 # LCLS-I @ 120 Hz
          RateSel: 0x0 # No triggering
          DestSel: 0x20000
        ###################
        LocalTrig[:]:
          EnableTrig: True
          Polarity: Rising
          Delay: 625000 # (156.25 MHz) x 4 ms = 625000
          Width: 0x1 # 0x1 = one cycle pulse
        LocalTrig[0]:
          Source: 0x0 # CH0
        # LocalTrig[1]:
          # Source: 0x1 # CH1
        # LocalTrig[2]:
          # Source: 0x2 # CH2
        # LocalTrig[3]:
          # Source: 0x3 # CH3  
        ###################
        RemoteTrig[:]:
          EnableTrig: True
          Polarity: Rising
          Delay: 0x0 # zero for low latency fiber trigger
          Width: 0x1 # 0x1 = one cycle pulse
        RemoteTrig[0]:
          Source: 0x0 # CH0
        # RemoteTrig[1]:
          # Source: 0x1 # CH1
        # RemoteTrig[2]:
          # Source: 0x2 # CH2
        # RemoteTrig[3]:
          # Source: 0x3 # CH3            
      ###################
      TimingFrameRx:
        ClkSel: 0x0 # 0x0 = LCLS-I timing
        RxDown: 0x0 # Reset the latching register
      ###################
      