TimeToolDev:
  enable: True
  ForceWrite: False
  Hardware:
    enable: True
    AxiPcieCore:
      enable: True
      AxiPciePhy:
        enable: True
      AxiVersion:
        enable: True
        ScratchPad: 0x000000
        FpgaReloadHalt: 0x0
        FpgaReloadAddress: 0x0
        UserReset: 0x0
      DmaIbAxisMon:
        enable: True
        CntRst: 0x0
      DmaObAxisMon:
        enable: True
        CntRst: 0x0
    PgpMon[0]:
      enable: True
      Loopback: 'No'
      LocData: 0x0
      LocDataEn: False
      AutoStatus: False
    PgpTxAxisMon[0]:
      enable: True
      CntRst: 0x0
    PgpRxAxisMon[0]:
      enable: True
      CntRst: 0x0
    Timing:
      enable: True
      GthRxAlignCheck[0]:
        enable: True
        PhaseTarget: 0x10
        ResetLen: 0x3
      GthRxAlignCheck[1]:
        enable: True
        PhaseTarget: 0x10
        ResetLen: 0x3
      TimingDbgMon:
        enable: True
        Loopback: 'No'
        UseMiniTpg: True
        CntRst: 0x0
      Triggering:
        enable: True
        Ch[0]:
          enable: True
          EnableReg: True
          RateSel: 0x1028
          DestSel: 0x20000
        LocalTrig[0]:
          enable: True
          EnableTrig: True
          Source: 0x0
          Polarity: Rising
          Delay: 0x0
          Width: 0x1
        RemoteTrig[0]:
          enable: True
          EnableTrig: True
          Source: 0x0
          Polarity: Rising
          Delay: 0x0
          Width: 0x1
      TimingFrameRx:
        enable: True
        RxCountReset: 0x0
        RxPolarity: 0x0
        RxReset: 0x0
        ClkSel: 0x0
        RxDown: 0x0
        BypassRst: 0x0
        RxPllReset: 0x0
        MsgDelay: 0x0
      TPGMiniCore:
        enable: True
        TxPolarity: 0x0
        TxLoopback: 0x0
        TxInhibit: 0x0
        BaseControl: 0xc8
        PulseIdWr: 0x0
        PulseIdSet: 0x0
        TStampWr: 0x0
        TStampSet: 0x0
        FixedRateDiv[0]: 0x1
        FixedRateDiv[1]: 0xd
        FixedRateDiv[2]: 0x5b
        FixedRateDiv[3]: 0x38e
        FixedRateDiv[4]: 0x238c
        FixedRateDiv[5]: 0x16378
        FixedRateDiv[6]: 0xde2b0
        FixedRateDiv[7]: 0x0
        FixedRateDiv[8]: 0x0
        FixedRateDiv[9]: 0x0
        RateReload: 0x0
        TxReset: 0x0
        CountIntervalReset: 0x0
        Lcls1BsaNumSamples: 0x0
        Lcls1BsaRate: 120Hz
        Lcls1BsaTimeSlot: TS1
        Lcls1BsaSeverity: INVALID
        Lcls1BsaEdefSlot: 0x0
        Lcls1BsaNumAvgs: 0x0
        Lcls1BsaStart: 0x0
        BsaCompleteWr: 0x0
        BsaActive[0]: 0x0
        BsaActive[1]: 0x0
        BsaRateSelMode[0]: FixedRate
        BsaRateSelMode[1]: FixedRate
        BsaFixedRate[0]: 1MHz
        BsaFixedRate[1]: 1MHz
        BsaACRate[0]: 60Hz
        BsaACRate[1]: 60Hz
        BsaACTSMask[0]: 0x3f
        BsaACTSMask[1]: 0x3f
        BsaSequenceSelect[0]: 0x0
        BsaSequenceSelect[1]: 0x0
        BsaSequenceBitSelect[0]: 0x0
        BsaSequenceBitSelect[1]: 0x0
        BsaDestMode[0]: Dont_Care
        BsaDestMode[1]: Dont_Care
        BsaDestInclusiveMask[0]: 0xffff
        BsaDestInclusiveMask[1]: 0xffff
        BsaDestExclusiveMask[0]: 0xffff
        BsaDestExclusiveMask[1]: 0xffff
        BsaNtoAvg[0]: 0x1
        BsaNtoAvg[1]: 0x1
        BsaAvgToWr[0]: 0x64
        BsaAvgToWr[1]: 0x0
        BsaMaxSeverity[0]: Invalid
        BsaMaxSeverity[1]: Invalid
        CountInterval: 0x488b
  ClinkFeb[0]:
    enable: True
    AxiVersion:
      enable: True
      ScratchPad: 0x000000
      FpgaReloadHalt: 0x0
      FpgaReloadAddress: 0x0
      UserReset: 0x0
    CypressS25Fl:
      enable: True
    BoardTemp:
      enable: True
      AlertMaskWrite: False
      AlertMask: False
      StopWrite: False
      Stop: False
      RcritMaskWrite: False
      RcritMask: False
      LcritMaskWrite: False
      LcritMask: False
      FaultQueueWrite: False
      FaultQueue: False
      ConvertRateWrite: 0x0
      ConvertRate: '16'
      LocalHighSetpointWrite: 0x0
      LocalHighSetpoint: 70
      LocalLowSetpointWrite: 0x0
      LocalLowSetpoint: 0
      RemoteHighSetpointHighByteWrite: 0x0
      RemoteHighSetpoint: 70
      RemoteLowSetpointHighByteWrite: 0x0
      RemoteLowSetpoint: 0
      RemoteTcritSetpoint: 100
      LocalTcritSetpoint: 85
      TcritHysteresis: 10
      AlertMode: False
    BoardPwr:
      enable: True
      Control: 0xc
    Xadc:
      enable: True
    ClinkTop:
      enable: True
      Ch[0]:
        enable: True
        LinkMode: Full
        DataMode: 8Bit
        FrameMode: Line
        TapCount: 0x4
        DataEn: True
        Blowoff: False
        SerThrottle: 10000
        BaudRate: 9600
        SwControlValue: 0x0
        SwControlEn: 0x0
        UartPiranha4:
          enable: True
          CCF: ''
          CLS: ''
          CLM: '2'
          CPA[0]: ''
          CPA[1]: ''
          CPA[2]: ''
          DST: ''
          FFM: ''
          FRS: ''
          GET: ''
          LPC: ''
          ROI[0]: ''
          ROI[1]: ''
          SAC: ''
          SAD[0]: ''
          SAD[1]: ''
          SAD[2]: ''
          SAM: ''
          SBH: ''
          SBR: ''
          SBV: ''
          SCD: ''
          SEM: '0'
          SET: '5000'
          SMM: ''
          SPF: '0'
          SSB: ''
          SSF: '3'
          SSG: ''
          STG: ''
          STM: '0'
          SVM: '1'
          USD: ''
          USL: ''
          USS: ''
    TrigCtrl[0]:
      enable: True
      EnableTrig: True
      InvCC: False
      TrigMap: ChA
      TrigPulseWidth: 0xfff
      TrigPulseWidthMicrosec: 32.768
      TrigMask: 0x1
      CntRst: 0x0
    TrigCtrl[1]:
      enable: True
      EnableTrig: True
      InvCC: False
      TrigMap: ChB
      TrigPulseWidth: 0xfff
      TrigPulseWidthMicrosec: 32.768
      TrigMask: 0x1
      CntRst: 0x0
    PgpMon[0]:
      enable: True
    PgpTxAxisMon[0]:
      enable: True
      CntRst: 0x0
    PgpRxAxisMon[0]:
      enable: True
      CntRst: 0x0
    PgpMon[1]:
      enable: True
    PgpTxAxisMon[1]:
      enable: True
      CntRst: 0x0
    PgpRxAxisMon[1]:
      enable: True
      CntRst: 0x0
  TimeToolRx:
    enable: True
  Application:
    enable: True
    AppLane[0]:
      enable: True
      EventBuilder:
        enable: True
        Bypass: 0x0
        Timeout: 0x0
        Blowoff: False
      Fex:
        enable: True
        ScratchPad: 0x000000
        AddValue: 0x0
      Prescale:
        enable: True
        ScratchPad: 0x000000
        DialInPreScaling: 0x5
