TimeToolDev:
  TimeToolRx:
    enable: True
  Application:
    enable: True
    AppLane[0]:
      enable: True
      EventBuilder:
        enable: True
        Bypass: 0x0
        Timeout: 0x0
        Blowoff: False
      Fex:
        enable: True
        ScratchPad: 0x000000
        AddValue: 0x0
      Prescale:
        enable: True
        ScratchPad: 0x000000
        DialInPreScaling: 0x0
  #########################################################################################################
