package: 
  name: lcls2_timetool
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python
     - rogue
     - git
     - gitpython
     - numpy
     - clink_gateway_fw_lib
     - l2si_core
     - lcls2_pgp_fw_lib
     - axi_pcie_core
     - lcls_timing_core

   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/surf
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: LCLS2 Timetool Software

