TimeToolDev:
  enable: True
  ForceWrite: False
  InitAfterConfig: True
  Hardware:
    enable: True
    AxiPcieCore:
      enable: True
      AxiPciePhy:
        enable: True
      AxiVersion:
        enable: True
        ScratchPad: 0x000000
        FpgaReloadHalt: 0x0
        FpgaReloadAddress: 0x0
        UserReset: 0x0
      DmaIbAxisMon:
        enable: True
        CntRst: 0x1
      DmaObAxisMon:
        enable: True
        CntRst: 0x1
    PgpMon[0]:
      enable: True
      Loopback: 'No'
      LocData: 0x0
      LocDataEn: False
      AutoStatus: False
    PgpTxAxisMon[0]:
      enable: True
      CntRst: 0x1
    PgpRxAxisMon[0]:
      enable: True
      CntRst: 0x1
    Timing:
      enable: True
      GthRxAlignCheck[0]:
        enable: True
        PhaseTarget: 0x10
        ResetLen: 0x3
      GthRxAlignCheck[1]:
        enable: True
        PhaseTarget: 0x10
        ResetLen: 0x3
      TimingDbgMon:
        enable: True
        Loopback: 'No'
        UseMiniTpg: True
        CntRst: 0x1
      Triggering:
        enable: True
        Ch[0]:
          enable: True
          EnableReg: True
          RateSel: 0x102b
          DestSel: 0x20000
        LocalTrig[0]:
          enable: True
          EnableTrig: True
          Source: 0x0
          Polarity: Rising
          Delay: 0x0
          Width: 0x1
        RemoteTrig[0]:
          enable: True
          EnableTrig: True
          Source: 0x0
          Polarity: Rising
          Delay: 0x0
          Width: 0x1
      TimingFrameRx:
        enable: True
        RxCountReset: 0x0
        RxPolarity: 0x0
        RxReset: 0x0
        ClkSel: 0x0
        RxDown: 0x0
        BypassRst: 0x0
        RxPllReset: 0x0
        MsgDelay: 0x0
      TPGMiniCore:
        enable: True
        TxPolarity: 0x0
        TxLoopback: 0x0
        TxInhibit: 0x0
        BaseControl: 0xc8
        PulseIdWr: 0x0
        PulseIdSet: 0x0
        TStampWr: 0x0
        TStampSet: 0x0
        FixedRateDiv[0]: 0x1
        FixedRateDiv[1]: 0xd
        FixedRateDiv[2]: 0x5b
        FixedRateDiv[3]: 0x38e
        FixedRateDiv[4]: 0x238c
        FixedRateDiv[5]: 0x16378
        FixedRateDiv[6]: 0xde2b0
        FixedRateDiv[7]: 0x0
        FixedRateDiv[8]: 0x0
        FixedRateDiv[9]: 0x0
        RateReload: 0x0
        TxReset: 0x0
        CountIntervalReset: 0x0
        Lcls1BsaNumSamples: 0x0
        Lcls1BsaRate: 120Hz
        Lcls1BsaTimeSlot: TS1
        Lcls1BsaSeverity: INVALID
        Lcls1BsaEdefSlot: 0x0
        Lcls1BsaNumAvgs: 0x0
        Lcls1BsaStart: 0x0
        BsaCompleteWr: 0x0
        BsaActive[0]: 0x0
        BsaActive[1]: 0x0
        BsaRateSelMode[0]: FixedRate
        BsaRateSelMode[1]: FixedRate
        BsaFixedRate[0]: 1MHz
        BsaFixedRate[1]: 1MHz
        BsaACRate[0]: 60Hz
        BsaACRate[1]: 60Hz
        BsaACTSMask[0]: 0x3f
        BsaACTSMask[1]: 0x3f
        BsaSequenceSelect[0]: 0x0
        BsaSequenceSelect[1]: 0x0
        BsaSequenceBitSelect[0]: 0x0
        BsaSequenceBitSelect[1]: 0x0
        BsaDestMode[0]: Dont_Care
        BsaDestMode[1]: Dont_Care
        BsaDestInclusiveMask[0]: 0xffff
        BsaDestInclusiveMask[1]: 0xffff
        BsaDestExclusiveMask[0]: 0xffff
        BsaDestExclusiveMask[1]: 0xffff
        BsaNtoAvg[0]: 0x1
        BsaNtoAvg[1]: 0x1
        BsaAvgToWr[0]: 0x64
        BsaAvgToWr[1]: 0x0
        BsaMaxSeverity[0]: Invalid
        BsaMaxSeverity[1]: Invalid
        CountInterval: 0x488b
  ClinkFeb[0]:
    enable: True
    AxiVersion:
      enable: True
      ScratchPad: 0x000000
      FpgaReloadHalt: 0x0
      FpgaReloadAddress: 0x0
      UserReset: 0x0
    CypressS25Fl:
      enable: True
    BoardTemp:
      enable: True
      AlertMaskWrite: True
      AlertMask: True
      StopWrite: False
      Stop: False
      RcritMaskWrite: False
      RcritMask: False
      LcritMaskWrite: False
      LcritMask: False
      FaultQueueWrite: False
      FaultQueue: False
      ConvertRateWrite: 0x8
      ConvertRate: '16'
      LocalHighSetpointWrite: 0x46
      LocalHighSetpoint: 70
      LocalLowSetpointWrite: 0x0
      LocalLowSetpoint: 0
      RemoteHighSetpointHighByteWrite: 0x46
      RemoteHighSetpoint: 70
      RemoteLowSetpointHighByteWrite: 0x0
      RemoteLowSetpoint: 0
      RemoteTcritSetpoint: 100
      LocalTcritSetpoint: 85
      TcritHysteresis: 10
      AlertMode: False
    BoardPwr:
      enable: True
      Control: 0xc
    Xadc:
      enable: True
    ClinkTop:
      enable: True
      RstPll: 0x0
      Ch[0]:
        enable: True
        LinkMode: Full
        DataMode: 8Bit
        FrameMode: Line
        TapCount: 0x8
        DataEn: True
        Blowoff: False
        SerThrottle: 10000
        BaudRate: 9600
        SwControlValue: 0x0
        SwControlEn: 0x0
        UartPiranha4:
          enable: True
          CCF: ''
          CLS: ''
          CLM: '2'
          CPA[0]: ''
          CPA[1]: ''
          CPA[2]: ''
          DST: ''
          FFM: ''
          FRS: ''
          GET: ''
          LPC: ''
          ROI[0]: ''
          ROI[1]: ''
          SAC: ''
          SAD[0]: ''
          SAD[1]: ''
          SAD[2]: ''
          SAM: ''
          SBH: ''
          SBR: ''
          SBV: ''
          SCD: ''
          SEM: '0'
          SET: '5000'
          SMM: ''
          SPF: '0'
          SSB: ''
          SSF: '3'
          SSG: ''
          STG: ''
          STM: '1'
          SVM: '0'
          USD: ''
          USL: ''
          USS: ''
      Pll[0]:
        enable: True
        PHASE_MUX[0]: 0x0
        HIGH_TIME[0]: 0x7
        LOW_TIME[0]: 0x7
        PHASE_MUX[1]: 0x0
        HIGH_TIME[1]: 0x1
        LOW_TIME[1]: 0x1
        PHASE_MUX[2]: 0x0
        HIGH_TIME[2]: 0x1
        LOW_TIME[2]: 0x1
        PHASE_MUX[3]: 0x0
        HIGH_TIME[3]: 0x1
        LOW_TIME[3]: 0x1
        PHASE_MUX[4]: 0x0
        HIGH_TIME[4]: 0x1
        LOW_TIME[4]: 0x1
        PHASE_MUX[5]: 0x0
        HIGH_TIME[5]: 0x1
        LOW_TIME[5]: 0x1
        PHASE_MUX[6]: 0x0
        HIGH_TIME[6]: 0x1
        LOW_TIME[6]: 0x1
        PHASE_MUX_FB: 0x0
        HIGH_TIME_FB: 0x7
        LOW_TIME_FB: 0x7
        FRAC[0]: 0x0
        FRAC_EN[0]: 0x0
        FRAC_WF_R[0]: 0x0
        MX[0]: 0x0
        EDGE[0]: 0x0
        NO_COUNT[0]: 0x0
        DELAY_TIME[0]: 0x0
        MX[1]: 0x0
        EDGE[1]: 0x0
        NO_COUNT[1]: 0x0
        DELAY_TIME[1]: 0x0
        MX[2]: 0x0
        EDGE[2]: 0x0
        NO_COUNT[2]: 0x1
        DELAY_TIME[2]: 0x0
        MX[3]: 0x0
        EDGE[3]: 0x0
        NO_COUNT[3]: 0x1
        DELAY_TIME[3]: 0x0
        MX[4]: 0x0
        EDGE[4]: 0x0
        NO_COUNT[4]: 0x1
        DELAY_TIME[4]: 0x0
        PHASE_MUX_F_CLKOUT[0]: 0x0
        FRAC_WF_F_CLKOUT[0]: 0x0
        MX[5]: 0x0
        EDGE[5]: 0x0
        NO_COUNT[5]: 0x1
        DELAY_TIME[5]: 0x0
        PHASE_MUX_F_CLKOUT_FB: 0x0
        FRAC_WF_F_CLKOUT_FB: 0x0
        MX[6]: 0x0
        EDGE[6]: 0x0
        NO_COUNT[6]: 0x1
        DELAY_TIME[6]: 0x0
        FRAC_FB: 0x0
        FRAC_EN_FB: 0x0
        FRAC_WF_R_FB: 0x0
        MX_FB: 0x0
        EDGE_FB: 0x0
        NO_COUNT_FB: 0x0
        DELAY_TIME_FB: 0x0
        EDGE_DIV: 0x0
        NO_COUNT_DIV: 0x1
        HIGH_TIME_DIV: 0x1
        LOW_TIME_DIV: 0x1
        LockReg[0]: 0x2bc
        LockReg[1]: 0x7c01
        LockReg[2]: 0xffe9
        FiltReg[0]: 0x9908
        FiltReg[1]: 0x8100
        POWER: 0xffff
      Pll[1]:
        enable: True
        PHASE_MUX[0]: 0x0
        HIGH_TIME[0]: 0x7
        LOW_TIME[0]: 0x7
        PHASE_MUX[1]: 0x0
        HIGH_TIME[1]: 0x1
        LOW_TIME[1]: 0x1
        PHASE_MUX[2]: 0x0
        HIGH_TIME[2]: 0x1
        LOW_TIME[2]: 0x1
        PHASE_MUX[3]: 0x0
        HIGH_TIME[3]: 0x1
        LOW_TIME[3]: 0x1
        PHASE_MUX[4]: 0x0
        HIGH_TIME[4]: 0x1
        LOW_TIME[4]: 0x1
        PHASE_MUX[5]: 0x0
        HIGH_TIME[5]: 0x1
        LOW_TIME[5]: 0x1
        PHASE_MUX[6]: 0x0
        HIGH_TIME[6]: 0x1
        LOW_TIME[6]: 0x1
        PHASE_MUX_FB: 0x0
        HIGH_TIME_FB: 0x7
        LOW_TIME_FB: 0x7
        FRAC[0]: 0x0
        FRAC_EN[0]: 0x0
        FRAC_WF_R[0]: 0x0
        MX[0]: 0x0
        EDGE[0]: 0x0
        NO_COUNT[0]: 0x0
        DELAY_TIME[0]: 0x0
        MX[1]: 0x0
        EDGE[1]: 0x0
        NO_COUNT[1]: 0x0
        DELAY_TIME[1]: 0x0
        MX[2]: 0x0
        EDGE[2]: 0x0
        NO_COUNT[2]: 0x1
        DELAY_TIME[2]: 0x0
        MX[3]: 0x0
        EDGE[3]: 0x0
        NO_COUNT[3]: 0x1
        DELAY_TIME[3]: 0x0
        MX[4]: 0x0
        EDGE[4]: 0x0
        NO_COUNT[4]: 0x1
        DELAY_TIME[4]: 0x0
        PHASE_MUX_F_CLKOUT[0]: 0x0
        FRAC_WF_F_CLKOUT[0]: 0x0
        MX[5]: 0x0
        EDGE[5]: 0x0
        NO_COUNT[5]: 0x1
        DELAY_TIME[5]: 0x0
        PHASE_MUX_F_CLKOUT_FB: 0x0
        FRAC_WF_F_CLKOUT_FB: 0x0
        MX[6]: 0x0
        EDGE[6]: 0x0
        NO_COUNT[6]: 0x1
        DELAY_TIME[6]: 0x0
        FRAC_FB: 0x0
        FRAC_EN_FB: 0x0
        FRAC_WF_R_FB: 0x0
        MX_FB: 0x0
        EDGE_FB: 0x0
        NO_COUNT_FB: 0x0
        DELAY_TIME_FB: 0x0
        EDGE_DIV: 0x0
        NO_COUNT_DIV: 0x1
        HIGH_TIME_DIV: 0x1
        LOW_TIME_DIV: 0x1
        LockReg[0]: 0x2bc
        LockReg[1]: 0x7c01
        LockReg[2]: 0xffe9
        FiltReg[0]: 0x9908
        FiltReg[1]: 0x8100
        POWER: 0xffff
      Pll[2]:
        enable: True
        PHASE_MUX[0]: 0x0
        HIGH_TIME[0]: 0x7
        LOW_TIME[0]: 0x7
        PHASE_MUX[1]: 0x0
        HIGH_TIME[1]: 0x1
        LOW_TIME[1]: 0x1
        PHASE_MUX[2]: 0x0
        HIGH_TIME[2]: 0x1
        LOW_TIME[2]: 0x1
        PHASE_MUX[3]: 0x0
        HIGH_TIME[3]: 0x1
        LOW_TIME[3]: 0x1
        PHASE_MUX[4]: 0x0
        HIGH_TIME[4]: 0x1
        LOW_TIME[4]: 0x1
        PHASE_MUX[5]: 0x0
        HIGH_TIME[5]: 0x1
        LOW_TIME[5]: 0x1
        PHASE_MUX[6]: 0x0
        HIGH_TIME[6]: 0x1
        LOW_TIME[6]: 0x1
        PHASE_MUX_FB: 0x0
        HIGH_TIME_FB: 0x7
        LOW_TIME_FB: 0x7
        FRAC[0]: 0x0
        FRAC_EN[0]: 0x0
        FRAC_WF_R[0]: 0x0
        MX[0]: 0x0
        EDGE[0]: 0x0
        NO_COUNT[0]: 0x0
        DELAY_TIME[0]: 0x0
        MX[1]: 0x0
        EDGE[1]: 0x0
        NO_COUNT[1]: 0x0
        DELAY_TIME[1]: 0x0
        MX[2]: 0x0
        EDGE[2]: 0x0
        NO_COUNT[2]: 0x1
        DELAY_TIME[2]: 0x0
        MX[3]: 0x0
        EDGE[3]: 0x0
        NO_COUNT[3]: 0x1
        DELAY_TIME[3]: 0x0
        MX[4]: 0x0
        EDGE[4]: 0x0
        NO_COUNT[4]: 0x1
        DELAY_TIME[4]: 0x0
        PHASE_MUX_F_CLKOUT[0]: 0x0
        FRAC_WF_F_CLKOUT[0]: 0x0
        MX[5]: 0x0
        EDGE[5]: 0x0
        NO_COUNT[5]: 0x1
        DELAY_TIME[5]: 0x0
        PHASE_MUX_F_CLKOUT_FB: 0x0
        FRAC_WF_F_CLKOUT_FB: 0x0
        MX[6]: 0x0
        EDGE[6]: 0x0
        NO_COUNT[6]: 0x1
        DELAY_TIME[6]: 0x0
        FRAC_FB: 0x0
        FRAC_EN_FB: 0x0
        FRAC_WF_R_FB: 0x0
        MX_FB: 0x0
        EDGE_FB: 0x0
        NO_COUNT_FB: 0x0
        DELAY_TIME_FB: 0x0
        EDGE_DIV: 0x0
        NO_COUNT_DIV: 0x1
        HIGH_TIME_DIV: 0x1
        LOW_TIME_DIV: 0x1
        LockReg[0]: 0x2bc
        LockReg[1]: 0x7c01
        LockReg[2]: 0xffe9
        FiltReg[0]: 0x9908
        FiltReg[1]: 0x8100
        POWER: 0xffff
      PllConfig[0]: ''
      PllConfig[1]: ''
      PllConfig[2]: ''
    TrigCtrl[0]:
      enable: True
      EnableTrig: True
      InvCC: False
      TrigMap: ChA
      TrigPulseWidthRaw: 0xfff
      TrigPulseWidth: 32.768
      TrigMask: 0x1
      CntRst: 0x1
    TrigCtrl[1]:
      enable: True
      EnableTrig: False
      InvCC: False
      TrigMap: ChB
      TrigPulseWidthRaw: 0xfff
      TrigPulseWidth: 32.768
      TrigMask: 0x1
      CntRst: 0x1
    PgpMon[0]:
      enable: True
    PgpTxAxisMon[0]:
      enable: True
      CntRst: 0x1
    PgpRxAxisMon[0]:
      enable: True
      CntRst: 0x1
    PgpMon[1]:
      enable: True
    PgpTxAxisMon[1]:
      enable: True
      CntRst: 0x1
    PgpRxAxisMon[1]:
      enable: True
      CntRst: 0x1
  TimeToolRx:
    enable: True
    frameLength: 2176
  Application:
    enable: True
    AppLane[0]:
      enable: True
      EventBuilder:
        enable: True
        Bypass: 0x0
        Timeout: 0x0
        Blowoff: False
      Fex:
        enable: True
        EventBuilder:
          enable: True
          Bypass: 0x0
          Timeout: 0x0
          Blowoff: False
        EVC_placeholder:
          enable: True
          ScratchPad: 0x000000
          DialInPreScaling: 0x0
        FIR:
          enable: True
          CoefficientSet0: 0x7f7f7f7f
          CoefficientSet1: 0x7f7f7f7f
          CoefficientSet2: 0x7f7f7f7f
          CoefficientSet3: 0x7f7f7f7f
          CoefficientSet4: 0x81818181
          CoefficientSet5: 0x81818181
          CoefficientSet6: 0x81818181
          CoefficientSet7: 0x81818181
          LoadCoefficients: 0x0
        FrameIIR:
          enable: True
          ScratchPad: 0x000000
          TimeConstant: 0x3
        background_prescaler:
          enable: True
          ScratchPad: 0x000000
          DialInPreScaling: 0xff
      Prescale:
        enable: True
        ScratchPad: 0x000000
        DialInPreScaling: 0xfe
      ByPass:
        enable: True
        ScratchPad: 0x000000
        ByPass: 0x0
